from __future__ import annotations

import pandas as pd


def normalize(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    rename = {
        "Ref": "product",
        "Product": "product",
        "Product Name": "product",
        "Coupon p.a. (%)": "coupon",
        "Fixed Coupon p.a. (%)": "coupon",
        "Phoenix Coupon p.a. (%)": "coupon",
        "Coupon (%)": "coupon",
        "Coupon p.a": "coupon",
        "Currency": "currency",
        "Ccy": "currency",
        "Tenor (m)": "tenor",
        "Tenor": "tenor",
        "Maturity (m)": "tenor",
        "Tenor in months": "tenor",
        "Strike (%)": "strike",
        "Strike %": "strike",
        "Strike Level": "strike",
        "KI Barrier (%)": "barrier",
        "Barrier Level": "barrier",
        "Phoenix Barrier Level (%)": "barrier",
        "Barrier (%)": "barrier",
        "KI Barrier": "barrier",
        "Reoffer (%)": "reoffer",
        "Reoffer": "reoffer",
        "Issue Price (%)": "reoffer",
        "Reoffer Price": "reoffer",
        "BBG Code 1": "underlying_1",
        "Underlying 1": "underlying_1",
        "Underlying_1": "underlying_1",
        "Ticker 1": "underlying_1",
        "BBG Code 2": "underlying_2",
        "Underlying 2": "underlying_2",
        "Underlying_2": "underlying_2",
        "Ticker 2": "underlying_2",
        "BBG Code 3": "underlying_3",
        "Underlying 3": "underlying_3",
        "Underlying_3": "underlying_3",
        "Ticker 3": "underlying_3",
        "BBG Code 4": "underlying_4",
        "Underlying 4": "underlying_4",
        "Underlying_4": "underlying_4",
        "Ticker 4": "underlying_4",
        "BBG Code 5": "underlying_5",
        "Underlying 5": "underlying_5",
        "Underlying_5": "underlying_5",
        "Ticker 5": "underlying_5",
        "Barrier Type": "barrier_type",
        "KI Type": "barrier_type",
        "Early Termination Level (%)": "autocall_barrier",
        "Autocall Level (%)": "autocall_barrier",
        "Autocall Trigger (%)": "autocall_barrier",
        "Early Termination Period": "autocall_frequency",
        "KO Frequency": "autocall_frequency",
        "Autocall Frequency": "autocall_frequency",
        "Non Autocallable Period": "no_call_period",
        "Non callable Period": "no_call_period",
        "No Call Period": "no_call_period",
    }
    df = df.rename(columns={k: v for k, v in rename.items() if k in df.columns})
    return df

